### ISSUE TITLE
Add header "Service-Worker-Allowed" for pwa support

### ISSUE THREAD

**Issue by mattmeye** [lwsjs/spa#4]
see: https://w3c.github.io/ServiceWorker/#service-worker-script-response

**Comment by 75lb** [comment]
add the `Service-Worker-Allowed` response header at which point? For which requests and with what value? 

Could we solve this with a command-line option? E.g. 

```
$ ws --spa app/index.html --spa.service-worker-allowed /app
```

Should the `Service-Worker-Allowed` response header be added for all requests or only those which return the spa file (i.e. non-asset requests)?

**Comment by 75lb** [comment]
Closing as it is not clear _when_ the `Service-Worker-Allowed` header should be included in the response and with what value.. It's not appropriate to implement a general rule to include the header with _all_ responses.

This feature seems more suited to a [custom middleware](https://github.com/lwsjs/local-web-server/wiki/Creating-middleware) containing your specific rules for when it should be included, and with what value.
